### ISSUE TITLE
[Android] Cannot set empty field

### ISSUE THREAD

**Issue by maticDevelo** [react-native-picker/picker#592]
On Android devices dropdown automatically selects first item. If i dont have Picker.item Select Property it would select Item 1. 
What it shoud do is if value is 0 or undefined not show a label. It should be empty field. I can achieve empty field if i set first Item label to empty string. However than in modal i have this empty block. 

The ideal would be if in modal it says Select Property label so user can click on that to reset field. And then the field should be empty. 

Is there a way to achieve this? The code is usuall. Picker component with item map of Picker.Items.

<img width="404" alt="Screenshot 2024-11-11 at 13 55 55" src="https://github.com/user-attachments/assets/1000eacd-9daf-44c2-a4b4-6843f3709a76">
<img width="392" alt="Screenshot 2024-11-11 at 13 56 02" src="https://github.com/user-attachments/assets/c512e3cc-7fb1-435e-9358-3dd37c8862bf">
<img width="376" alt="Screenshot 2024-11-11 at 14 05 09" src="https://github.com/user-attachments/assets/3379a6ec-5220-4ef2-ab8a-c594c6d70d3a">
<img width="392" alt="Screenshot 2024-11-11 at 14 01 08" src="https://github.com/user-attachments/assets/f601c6c5-c5e0-4373-bf5e-09cc0b8ae2f5">

**Comment by dmk3141618** [comment]
Same issue on Android. 

I can set empty string as a value on the iOS device.

But I can not set empty string as a value on the Android device. It does not trigger onValueChange.
value is '', 'option1', 'option2' 
then '' >> 'option1' , it triggers onValueChange.
then 'option1' >> 'option2' , it triggers onValueChange.
But 'option2' >> '' , it does not trigger onValueChange.
So I can not reset value to the empty state.

on the iOS device, it works.

**Comment by dmk3141618** [comment]
Any updates? Sorry but I really need this fixed.

**Comment by jeffnian88** [comment]
Hi all,

is there any update?

**Comment by vincicat** [comment]
not a very useful update: you can't select the empty string Item because falsy value on Android will not trigger `onValueChange` (see https://github.com/react-native-picker/picker/issues/608)
in the long term, that require the contributors to fix the data type on Android; In the short term, there is a trick: you can use **whitespace** as the empty value placeholder. 

So the "empty field" will be something like this:

```jsx
<Picker.Item value=" " label="" />
```

and in the function that processing the selected value....
```js
valueProcessor = (v = "")=>{ 
    v = v.trim(); // clean up: placeholder value will be a empty string now
    /* remaining tasks */ 
}
```
[demo](https://snack.expo.dev/1R-5hVI9LtrskH7wf1cKP)

**Comment by pranshuchittora** [comment]
This issue has been fixed via #604 and is available in the latest version of the lib

**Comment by bladeSk** [comment]
This is still broken. While the picker now works with falsy values, it still doesn't support having nothing selected and defaults to the first item.
